<?php
$games = [
  ["slug"=>"roblox", "title"=>"Roblox", "image"=>"game-images/roblox.jpg", "description"=>"Roblox is a massive online platform where millions of players come together to imagine, create, and share 3D virtual worlds and experiences. With an intuitive game creation system, players can build anything from obstacle courses to role-playing games, then share their creations with a global community. The platform offers endless variety with games spanning multiple genres, from action-adventure and simulation to role-playing and tycoon games. Regular updates and a thriving community ensure there's always something new to discover, making it a favorite among players of all ages who enjoy creativity and social gaming experiences.", "genres"=>["Adventure","Social","Simulation"], "categories"=>["Adventure","Social","Simulation","Multiplayer","User-Generated","Free-to-Play","Sandbox","Cross-Platform"], "platforms"=>["PC","Mobile","Xbox","PlayStation"]],
  ["slug"=>"spider-man-2", "title"=>"Marvel's Spider-Man 2", "image"=>"game-images/spider-man-2.jpg", "description"=>"In this highly anticipated sequel, players take on the dual roles of Peter Parker and Miles Morales as they navigate the challenges of being superheroes while balancing their personal lives. The game expands on the beloved web-swinging mechanics and combat system from its predecessors, introducing new abilities for both Spider-Men. The story delves deeper into the characters' relationships and features a rogues' gallery of iconic villains. The open-world New York City is more detailed than ever, with dynamic weather, improved graphics, and seamless transitions between the two playable characters. With an emotional narrative and thrilling set pieces, Spider-Man 2 delivers an unforgettable superhero experience.", "genres"=>["Action","Open World"], "categories"=>["Action","Adventure","Open World","Superhero"], "platforms"=>["PlayStation"]],
  ["slug"=>"star-wars-jedi-survivor", "title"=>"Star Wars Jedi: Survivor", "image"=>"game-images/jedi-survivor.jpg", "description"=>"Continue the journey of Cal Kestis...", "genres"=>["Action","Adventure"], "categories"=>["Action","Adventure","RPG","Sci-Fi"], "platforms"=>["PC","PlayStation","Xbox"]],
  ["slug"=>"fortnite", "title"=>"Fortnite", "image"=>"game-images/fortnite.jpg", "description"=>"Battle royale with building mechanics...", "genres"=>["Battle Royale","Shooter"], "categories"=>["Shooter","Battle Royale","Multiplayer","Free-to-Play"], "platforms"=>["PC","PlayStation","Xbox","Nintendo Switch","Mobile"]],
  ["slug"=>"gtav", "title"=>"Grand Theft Auto V", "image"=>"game-images/GTAV.jpg", "description"=>"Sprawling open-world action in Los Santos...", "genres"=>["Action","Open World"], "categories"=>["Action","Open World","Adventure","Crime","Multiplayer"], "platforms"=>["PC","PlayStation","Xbox"]],
  // ... (add more from your games.js as needed) ...
];
